import { test, expect } from '@playwright/test';
test('dashboard filters, themes, navigation and integration lifecycle', async ({ page, request }) => {
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/dashboard');
 await expect(page.getByRole('heading',{name:'Consumption overview'})).toBeVisible();
 await expect(page.locator('.kpi-value').first()).toHaveText('1.45M');
 await expect(page.locator('canvas').first()).toBeVisible();
 await page.screenshot({path:'../artifacts/dashboard-light.png',fullPage:true});
 await page.getByLabel('Provider filter',{exact:true}).selectOption('Claude');
 await expect(page.locator('.provider-panel tbody tr')).toHaveCount(1);
 await page.getByLabel('Account filter',{exact:true}).selectOption('claude-dev');
 await expect(page.locator('.kpi-value').first()).not.toHaveText('1.45M');
 await page.getByRole('button',{name:'Reset filters',exact:true}).click();
 await expect(page.locator('.provider-panel tbody tr')).toHaveCount(4);
 await page.getByRole('button',{name:'Switch to dark mode'}).click();
 await expect(page.locator('html')).toHaveClass('dark');
 await page.screenshot({path:'../artifacts/dashboard-dark.png',fullPage:true});
 await page.getByRole('button',{name:'Switch to light mode'}).click();
 for(const [link,heading] of [['Usage Analytics','Usage analytics'],['Cost Analytics','Cost analytics'],['Providers','Providers'],['Accounts','Accounts'],['Reports','Reports'],['Alerts','Alerts'],['Audit Logs','Audit logs'],['Settings','Workspace settings']]){
  await page.getByRole('navigation').getByRole('link',{name:link,exact:true}).click();
  await expect(page.getByRole('heading',{name:heading,exact:true,level:1})).toBeVisible();
  await expect(page.locator('ui-loading')).toHaveCount(0);
  await expect(page.locator('ui-error')).toHaveCount(0);
 }
 await page.getByRole('navigation').getByRole('link',{name:'Reports',exact:true}).click();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download report'}).click();expect((await download).suggestedFilename()).toContain('.csv');
 await page.getByRole('navigation').getByRole('link',{name:'Integrations',exact:true}).click();
 await expect(page.locator('tbody tr')).toHaveCount(6);
 await page.getByRole('link',{name:'Add integration',exact:true}).click();
 await page.getByRole('button',{name:'Anthropic Claude Enterprise language models'}).click();
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByRole('textbox',{name:'Integration name',exact:true}).fill('Browser verification Claude');
 await page.getByLabel('Admin API key',{exact:true}).fill('invalid-key');
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByRole('button',{name:'Test connection',exact:true}).click();
 await expect(page.getByText('AuthenticationFailed',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Back',exact:true}).click();
 await page.getByLabel('Admin API key',{exact:true}).fill('browser-demo-credential');
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByRole('button',{name:'Test connection',exact:true}).click();
 await expect(page.getByText('Connected — Demo Mode',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Review integration',exact:true}).click();
 await expect(page.locator('.review-list')).not.toContainText('browser-demo-credential');
 await page.screenshot({path:'../artifacts/integration-review.png',fullPage:true});
 await page.getByRole('button',{name:'Add integration',exact:true}).click();
 await expect(page.getByRole('heading',{name:'You’re connected'})).toBeVisible();
 const integrations=await (await request.get('http://localhost:5080/api/integrations')).json();
 const added=integrations.find((i:{integrationName:string})=>i.integrationName==='Browser verification Claude');
 expect(added).toBeTruthy();expect(JSON.stringify(integrations)).not.toContain('browser-demo-credential');
 await page.getByRole('button',{name:'Run initial sync'}).click();
 await expect(page.getByRole('button',{name:'Browser verification Claude',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Actions for Browser verification Claude'}).click();
 await page.getByRole('menuitem',{name:'Disable',exact:true}).click();
 await expect(page.locator('tr').filter({hasText:'Browser verification Claude'})).toContainText('Disabled');
 await page.getByRole('button',{name:'Actions for Browser verification Claude'}).click();
 await page.getByRole('menuitem',{name:'Delete integration',exact:true}).click();
 await page.getByRole('dialog').getByRole('button',{name:'Delete integration',exact:true}).click();
 await expect(page.getByRole('button',{name:'Browser verification Claude',exact:true})).toHaveCount(0);
 await page.goto('/dashboard');await expect(page.locator('.kpi-value').first()).toHaveText('1.45M');
 await page.setViewportSize({width:768,height:1024});await page.screenshot({path:'../artifacts/dashboard-tablet.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'../artifacts/dashboard-mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 expect(errors).toEqual([]);
});
test('custom REST schema and empty/error states',async({page})=>{
 await page.goto('/integrations/add');
 await page.getByRole('button',{name:'Custom REST API Configure another AI or SaaS provider'}).click();
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await expect(page.getByRole('textbox',{name:'Response mapping (JSON)',exact:true})).toBeVisible();
 await page.getByRole('combobox',{name:'Authentication type',exact:true}).selectOption('Basic');
 await expect(page.getByLabel('Password',{exact:true})).toBeVisible();
 await expect(page.getByLabel('API key / admin key / token',{exact:true})).toHaveCount(0);
 await page.goto('/dashboard');await expect(page.locator('.kpi-value').first()).toBeVisible();
 await page.getByLabel('Provider filter',{exact:true}).selectOption('CustomREST');
 await expect(page.getByRole('heading',{name:'No usage for this selection'})).toBeVisible();
 await page.locator('ui-empty').getByRole('button',{name:'Reset filters',exact:true}).click();
 await expect(page.locator('.kpi-value').first()).toHaveText('1.45M');
 await page.route('**/api/dashboard/summary**',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({title:'Service temporarily unavailable'})}));
 await page.getByRole('button',{name:'Refresh data'}).click();
 await expect(page.getByRole('alert')).toContainText('Service temporarily unavailable');
});

test('custom REST add, view and edit retain a secure runtime configuration',async({page,request})=>{
 await page.goto('/integrations/add');
 await page.getByRole('button',{name:'Custom REST API Configure another AI or SaaS provider'}).click();
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByRole('textbox',{name:'Integration name',exact:true}).fill('Browser verification Custom');
 await page.getByRole('textbox',{name:'Provider name',exact:true}).fill('Example AI');
 await page.getByRole('textbox',{name:'Base endpoint',exact:true}).fill('https://demo.example.com');
 await page.getByRole('textbox',{name:'Usage endpoint path',exact:true}).fill('/usage');
 await page.getByRole('combobox',{name:'Authentication type',exact:true}).selectOption('Bearer');
 await page.getByLabel('API key / admin key / token',{exact:true}).fill('custom-demo-secret');
 await page.getByRole('combobox',{name:'HTTP method',exact:true}).selectOption('GET');
 await page.getByRole('textbox',{name:'Response mapping (JSON)',exact:true}).fill('{"requests":"data.requests","timestamp":"data.date"}');
 await page.getByRole('textbox',{name:'Custom headers (JSON)',exact:true}).fill('{"X-Demo":"protected-header-value"}');
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByRole('button',{name:'Test connection',exact:true}).click();
 await expect(page.getByText('Connected — Demo Mode',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Review integration',exact:true}).click();
 await expect(page.locator('.review-list')).not.toContainText('protected-header-value');
 await page.getByRole('button',{name:'Add integration',exact:true}).click();
 await page.getByRole('button',{name:'Run initial sync'}).click();
 await page.getByRole('button',{name:'Browser verification Custom',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'Integration details'})).toContainText('0 records');
 await page.getByRole('dialog').getByRole('link',{name:'Edit integration'}).click();
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByRole('textbox',{name:'Integration name',exact:true}).fill('Browser verification Custom edited');
 await page.getByLabel('API key / admin key / token',{exact:true}).fill('custom-demo-secret-updated');
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByRole('button',{name:'Test connection',exact:true}).click();
 await page.getByRole('button',{name:'Review integration',exact:true}).click();
 await page.getByRole('button',{name:'Save changes',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Integration updated',exact:true})).toBeVisible();
 const list=await (await request.get('http://localhost:5080/api/integrations')).json();
 const integration=list.find((i:{integrationName:string})=>i.integrationName==='Browser verification Custom edited');
 expect(integration).toBeTruthy();expect(JSON.stringify(list)).not.toContain('custom-demo-secret');expect(JSON.stringify(list)).not.toContain('protected-header-value');
 expect((await request.delete('http://localhost:5080/api/integrations/'+integration.id)).status()).toBe(204);
});
